lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-accurascoperna_logo_light.png
    - docs/images/nf-core-accurascoperna_logo_light.png
    - docs/images/nf-core-accurascoperna_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-accurascoperna_logo_light.png
    - docs/images/nf-core-accurascoperna_logo_light.png
    - docs/images/nf-core-accurascoperna_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
repository_type: pipeline
template:
  author: zhouyiqi
  description: Pipeline to analyze AccuraSCOPE RNA data
  name: accurascoperna
  prefix: singleron-RD
  skip:
    - github_badges
    - igenomes
