repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: parameter_docs
        name: parameter_docs
        entry: nf-core schema docs -f -o docs/parameters.md
        language: system
        pass_filenames: false
